import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { extractText } from "./index.js";

// Fixtures are generated by scripts/gen-fixtures.mjs and committed. If they are
// somehow absent, these tests self-skip rather than fail — but in CI they are
// present, so the pdf/docx decoders are genuinely exercised.
const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "test", "fixtures");
const docxPath = join(fixturesDir, "sample-resume.docx");
const pdfPath = join(fixturesDir, "sample-resume.pdf");

test("extractText reads a real .docx resume fixture", async (t) => {
  if (!existsSync(docxPath)) {
    t.skip("fixture missing — run `npm run gen-fixtures -w @resume-prep/documents`");
    return;
  }
  const text = await extractText({ format: "docx", path: docxPath });
  assert.match(text, /Jane Developer/);
  assert.match(text, /Acme Corp/);
  assert.match(text, /TypeScript/);
});

test("extractText reads a real .pdf resume fixture", async (t) => {
  if (!existsSync(pdfPath)) {
    t.skip("fixture missing — run `npm run gen-fixtures -w @resume-prep/documents`");
    return;
  }
  const text = await extractText({ format: "pdf", path: pdfPath });
  assert.match(text, /Jane Developer/);
  assert.match(text, /Software Engineer/);
});

test("extractText accepts .docx bytes via a buffer", async (t) => {
  if (!existsSync(docxPath)) {
    t.skip("fixture missing — run `npm run gen-fixtures -w @resume-prep/documents`");
    return;
  }
  const buffer = new Uint8Array(await readFile(docxPath));
  const text = await extractText({ format: "docx", buffer });
  assert.match(text, /Jane Developer/);
});
